import type { SongModel } from '@/types';

export const songs: SongModel[] = [
  {
    id: 1,
    title: 'Adagio For Square',
    artist: 'Worakls',
    duration: '5:40',
    src: '/assets/Adagio for Square.mp3',
  },
  {
    id: 2,
    title: 'Art Of Silence',
    artist: 'Chilled Pigs',
    duration: '4:17',
    src: '/assets/Art of Silence.mp3',
  },
  {
    id: 3,
    title: 'Can You Hear The Music',
    artist: 'Ludwig Goransson',
    duration: '1:50',
    src: '/assets/Can You Hear The Music.mp3',
  },
  {
    id: 4,
    title: "Comptine d'un autre été, l'après-midi",
    artist: 'Yann Tiersen',
    duration: '2:14',
    src: "/assets/Comptine d'un autre été, l'après-midi.mp3",
  },
  {
    id: 5,
    title: 'Extrapolated',
    artist: 'Sumiruna',
    duration: '3:56',
    src: '/assets/Extrapolated.mp3',
  },
  {
    id: 6,
    title: 'Golden Hour (Piano Instrumental)',
    artist: 'Chilled Pigs',
    duration: '4:33',
    src: '/assets/golden hour (piano instrumental).mp3',
  },
  {
    id: 7,
    title: 'Electric Joke.mp3',
    artist: 'Kala & Shadow Shaman',
    duration: '4:47',
    src: '/assets/Kala & Shadow Shaman - Electric Joke.mp3',
  },
  {
    id: 8,
    title: 'Borders',
    artist: 'KALANDRA',
    duration: '3:22',
    src: '/assets/KALANDRA - _Borders_.mp3',
  },
  {
    id: 9,
    title: 'Mesmerized (Official Video)',
    artist: 'Monolink',
    duration: '4:08',
    src: '/assets/Monolink - Mesmerized (Official Video).mp3',
  },
  {
    id: 10,
    title: 'Nectar Drop',
    artist: 'DJ Prez',
    duration: '5:15',
    src: '/assets/Nectar Drop.mp3',
  },
  {
    id: 11,
    title: 'Emotive Motive (Sonic Tickle Remix)',
    artist: 'Sensient',
    duration: '4:42',
    src: '/assets/Sensient - Emotive Motive (Sonic Tickle Remix).mp3',
  },
  {
    id: 12,
    title: "Hvitserk's choice",
    artist: 'Trevor Morris',
    duration: '6:03',
    src: "/assets/Trevor Morris - Hvitserk's choice _ The Vikings Final Season (Music from the TV Series).mp3",
  },
  {
    id: 13,
    title: 'Valkyrja',
    artist: 'Unknown',
    duration: '6:03',
    src: '/assets/Valkyrja (Extended).mp3',
  },
  {
    id: 14,
    title: 'snowfall (slowed)',
    artist: 'øneheart x reidenshi',
    duration: '6:03',
    src: '/assets/øneheart x reidenshi - snowfall (slowed).mp3',
  },
];
